### ISSUE TITLE
Could the compute_ranks() function in the evaluate_ppi.py file test the concept_assertion relationship?

### ISSUE THREAD

**Issue by code-gamer** [KRR-Oxford/BoxSquaredEL#1]
Hi,
As the title says, I found out the code in compute_ranks() does not contain any info about protein's classes, but concept_assertion relationship does exsist in training stage. And my question is whether it can test such relationship?

**Comment by mathiasj33** [comment]
Hi,

At the moment, `evaluate_ppi.py` only supports testing protein interactions and not concept assertions.

However, it should not be difficult to adjust the code to evaluate concept assertions. The embeddings of individuals are saved in `model.individual_embeds` and the concept embeddings can be obtained with `model.get_boxes(model.class_embeds)`. You would then only have to compute the distances between the individual embeddings and the concept boxes / or check if the individuals are contained in the concept boxes. This should be quite similar to the implementation of `compute_nf1_ranks` in `evaluate.py`.

Hope this is helpful!

**Comment by code-gamer** [comment]
Hi,

Thanks for your timely reply. I did some thinking before asking the question, and this approach should work. I will try.

Thanks again.
